version: '3.8'

services:
  loanapplicationservice:
    build:
      context: ./loanapplicationservice
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq

  customerservice:
    build:
      context: ./CustomerService
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./RabbitMq/etc/definition.json:/etc/rabbitmq/definitions.json
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_ERLANG_COOKIE: 'rabbitcookie'
      RABBITMQ_NODENAME: 'rabbit@localhost'
      RABBITMQ_CONFIG_FILE: '/etc/rabbitmq/definitions.json'