version: '3.8'

networks:
  loaneval:
    driver: bridge

services:
  rabbitmq:
    image: rabbitmq:3.9-management-alpine
    hostname: my-rabbit
    container_name: my-rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - loaneval
    volumes:
      - ./rabbitmq/etc/definitions.json:/etc/rabbitmq/definitions.json
      - ./rabbitmq/etc/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./rabbitmq/data:/var/lib/rabbitmq/mnesia/rabbit@my-rabbit
      - ./rabbitmq/logs:/var/log/rabbitmq/log
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 30s
      timeout: 10s
      retries: 5

  loanapplicationservice:
    build:
      context: ./LoanApplicationService
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - rabbitmq
    networks:
      - loaneval

  customerservice:
    build:
      context: ./CustomerService
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - rabbitmq
    networks:
      - loaneval
    
  customerportal:
    build:
      context: ./customer-portal-app
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    environment:
      - NODE_ENV=development
    networks:
      - loaneval
    depends_on:
      - customerservice

  loanapplicationportal:
    build:
      context: ./loan-application-portal
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    networks:
      - loaneval
    depends_on:
      - loanapplicationservice